version: '3'
services:
  postgres:
    image: postgres:14
    container_name: java-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
