create table ACCOUNTS
(    account_Id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null ,
    account_Number serial,
    type varchar not null,
    user_id int references users(user_id),
    openDate date not null default now()
)